### PR TITLE
Let the player play as O

### PR DESCRIPTION
**Pull request by LyubomirT**
This update enhances the game by letting the player select their preferred symbol (X or O) before starting.

- Added an initial selection screen for choosing X or O
- Modified game logic to accommodate either symbol for player and AI
- Implemented AI's first move when it plays as X
- Updated minimax algorithm to work with flexible player/AI symbols

Hope this is helpful!

### CODE REVIEW

**Comment by DiscoverProgramming** [comment]
Cannot test code currently. Laptop under repair. Will definitely test and merge when I can. Thank you!

**Comment by LyubomirT** [comment]
Okay! Hope it gets fixed soon!

**Comment by DiscoverProgramming** [comment]
Again, I truly appreciate your help.

**Comment by DiscoverProgramming** [comment]
> Okay! Hope it gets fixed soon!

@LyubomirT Was wondering if you knew by chance or not if there is a way to see Tkinter GUI apps on GitHub Codespaces?

**Comment by LyubomirT** [comment]
> > Okay! Hope it gets fixed soon!
> 
> @LyubomirT Was wondering if you knew by chance or not if there is a way to see Tkinter GUI apps on GitHub Codespaces?

I honestly don't think there is a good way to do that, since Codespaces don't have a GUI output. Although you can try Replit for that, they have a screen emulator there.

**Comment by DiscoverProgramming** [comment]
> > > Okay! Hope it gets fixed soon!
> > 
> > 
> > @LyubomirT Was wondering if you knew by chance or not if there is a way to see Tkinter GUI apps on GitHub Codespaces?
> 
> I honestly don't think there is a good way to do that, since Codespaces don't have a GUI output. Although you can try Replit for that, they have a screen emulator there.

Oh, OK! Thanks. I will definitely look into that.

**Comment by DiscoverProgramming** [comment]
> > > Okay! Hope it gets fixed soon!
> > 
> > 
> > @LyubomirT Was wondering if you knew by chance or not if there is a way to see Tkinter GUI apps on GitHub Codespaces?
> 
> I honestly don't think there is a good way to do that, since Codespaces don't have a GUI output. Although you can try Replit for that, they have a screen emulator there.

I am probably not looking in the right place. Can you send me a link, please? I can't find it for some reason.

**Comment by LyubomirT** [comment]
> > > > Okay! Hope it gets fixed soon!
> > > 
> > > 
> > > @LyubomirT Was wondering if you knew by chance or not if there is a way to see Tkinter GUI apps on GitHub Codespaces?
> > 
> > 
> > I honestly don't think there is a good way to do that, since Codespaces don't have a GUI output. Although you can try Replit for that, they have a screen emulator there.
> 
> I am probably not looking in the right place. Can you send me a link, please? I can't find it for some reason.

https://replit.com/repls

**Comment by DiscoverProgramming** [comment]
> > > > > Okay! Hope it gets fixed soon!
> > > > 
> > > > 
> > > > @LyubomirT Was wondering if you knew by chance or not if there is a way to see Tkinter GUI apps on GitHub Codespaces?
> > > 
> > > 
> > > I honestly don't think there is a good way to do that, since Codespaces don't have a GUI output. Although you can try Replit for that, they have a screen emulator there.
> > 
> > 
> > I am probably not looking in the right place. Can you send me a link, please? I can't find it for some reason.
> 
> https://replit.com/repls

Thank you so much for your help!!! You have been extremely helpful to me.

**Pull request merged**
